#!/bin/bash
set -e 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/.api

STATE="$DIR/state"
if [ -f $STATE ];
then
  echo -n "State file already exists, do you want to make a backup (Y/n)? " 
  IFS= read -r answer
  if [ "$answer" == "Y" -o "$answer" == "y" ];
  then 
    mv $STATE $STATE.backup
  fi
fi

# create VPC
VPC_ID=$($BIN/ec2-create-vpc 10.10.0.0/16 | awk '{print $2}')
$BIN/ec2-create-tags $VPC_ID -t 'Name=ctf101'

# create dhcp-options and associate then with VPC
DHCP_ID=$($BIN/ec2-create-dhcp-options 'domain-name=ctf101' 'domain-name-servers=8.8.8.8' | awk '/DHCPOPTIONS/ {print $2}')
$BIN/ec2-create-tags $DHCP_ID -t 'Name=ctf101-dhcpoptions'
$BIN/ec2-associate-dhcp-options -c $VPC_ID $DHCP_ID

# create an internet gateway
INETGW_ID=$($BIN/ec2-create-internet-gateway | awk '{print $2}')
$BIN/ec2-create-tags $INETGW_ID -t 'Name=ctf101-inetgw'
$BIN/ec2-attach-internet-gateway -c $VPC_ID $INETGW_ID

# get automatically created routing table and attach it to the internet gateway
RT_ID=$($BIN/ec2-describe-route-tables | awk "/ROUTETABLE/ && /$VPC_ID/ {print \$2}")
$BIN/ec2-create-tags $RT_ID -t 'Name=ctf101-rt'

# add default route to the internet in routing table
$BIN/ec2-create-route $RT_ID -r 0.0.0.0/0 -g $INETGW_ID

# create subnets and associate to routing table
WEBTIER_ID=$($BIN/ec2-create-subnet -c $VPC_ID -i 10.10.1.0/24 | awk '{print $2}')
$BIN/ec2-create-tags $WEBTIER_ID -t 'Name=web-tier'
$BIN/ec2-associate-route-table -s $WEBTIER_ID $RT_ID
APPTIER_ID=$($BIN/ec2-create-subnet -c $VPC_ID -i 10.10.2.0/24 | awk '{print $2}')
$BIN/ec2-create-tags $APPTIER_ID -t 'Name=app-tier'
$BIN/ec2-associate-route-table -s $APPTIER_ID $RT_ID
DATATIER_ID=$($BIN/ec2-create-subnet -c $VPC_ID -i 10.10.10.0/24 | awk '{print $2}')
$BIN/ec2-create-tags $DATATIER_ID -t 'Name=data-tier'
$BIN/ec2-associate-route-table -s $DATATIER_ID $RT_ID
MGMTTIER_ID=$($BIN/ec2-create-subnet -c $VPC_ID -i 10.10.100.0/24 | awk '{print $2}')
$BIN/ec2-create-tags $MGMTTIER_ID -t 'Name=mgmt-tier'
$BIN/ec2-associate-route-table -s $MGMTTIER_ID $RT_ID

# Create VPC security group
SECPUB_ID=$($BIN/ec2-create-group -c $VPC_ID -d 'ctf101 firewall' ctf101-public | awk '{print $2}')

# create allow all rules
$BIN/ec2-authorize $SECPUB_ID -P icmp -t -1:-1
$BIN/ec2-authorize $SECPUB_ID -P tcp -p -1
$BIN/ec2-authorize $SECPUB_ID -P udp -p -1
$BIN/ec2-authorize --egress $SECPUB_ID -P icmp -t -1:-1
$BIN/ec2-authorize --egress $SECPUB_ID -P tcp -p -1
$BIN/ec2-authorize --egress $SECPUB_ID -P udp -p -1

# export variables to file
echo "VPC_ID=${VPC_ID}" > $STATE
echo "DHCP_ID=${DHCP_ID}" >> $STATE
echo "INETGW_ID=${INETGW_ID}" >> $STATE
echo "RT_ID=${RT_ID}" >> $STATE
echo "WEBTIER_ID=${WEBTIER_ID}" >> $STATE
echo "APPTIER_ID=${APPTIER_ID}" >> $STATE
echo "DATATIER_ID=${DATATIER_ID}" >> $STATE
echo "MGMTTIER_ID=${MGMTTIER_ID}" >> $STATE
echo "SECPUB_ID=${SECPUB_ID}" >> $STATE
echo "T1_IP"='10.10.1.254' >> $STATE
echo "T2_IP"='10.10.2.100' >> $STATE
echo "T3_IP"='10.10.2.101' >> $STATE
echo "T4_IP"='10.10.10.10' >> $STATE
echo "T5_IP"='10.10.100.254' >> $STATE
