#!/bin/bash
set -e
# Setup AWS
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/.api
STATE="$DIR/state"
if [ ! -f $STATE ];
then
  echo -n "cannot read state file: $STATE"
  exit 1
fi
source $STATE

## DELETE
$BIN/ec2-delete-subnet $WEBTIER_ID
$BIN/ec2-delete-subnet $APPTIER_ID
$BIN/ec2-delete-subnet $DATATIER_ID
$BIN/ec2-delete-subnet $MGMTTIER_ID
$BIN/ec2-detach-internet-gateway -c $VPC_ID $INETGW_ID
$BIN/ec2-delete-internet-gateway $INETGW_ID
$BIN/ec2-delete-route -r 0.0.0.0/0 $RT_ID
$BIN/ec2-delete-group $SECPUB_ID
$BIN/ec2-delete-vpc $VPC_ID
$BIN/ec2-delete-dhcp-options $DHCP_ID
rm $STATE
